### PR TITLE
Upgrade module to support terraform 0.15.0

### PR DESCRIPTION
**Pull request by riesbl01**

### CODE REVIEW

**Comment by faraday23** [comment]
LGTM

**Review by dutsmiller — CHANGES_REQUESTED** [review]
fix spacing

**Comment by dutsmiller** [comment]
This will be resolved with:  https://github.com/Azure-Terraform/terraform-azurerm-storage-account/pull/8

**Review by riesbl01 — COMMENTED** [review]
Looks good

**Comment by riesbl01** [comment]
> This will be resolved with: #8

If its going to be fixed with PR 8, can I close this PR down?

**Pull request closed without merging**
